### ISSUE TITLE
[Bug] Github Copilot stuck in the same window

### ISSUE THREAD

**Issue by mdabir1203** [skills/copilot-codespaces-vscode#116]
### Summary

Github Copilot not allowing me to signin in the new github codespaces

### How to reproduce

1. Go to 'github codespace'
2. Click on 'copilot extension icon'
3. Click on "Sign in"
4. Stuck in the same window 

<img width="376" alt="image" src="https://github.com/skills/copilot-codespaces-vscode/assets/66947064/80333a6b-7397-4a93-b12c-f5adb0013826">

**Comment by rsese** [comment]
👋 !  Just to clarify, which step in the course are you stuck?  I did a quick search and didn't see where the course mentions signing-in.

**Comment by mdabir1203** [comment]
It shows me once I access the codespaces

**Comment by hectorsector** [comment]
👋 @mdabir1203 I'll close this issue out as I don't believe it's an issue with the course. If you're having trouble with Codespaces or Copilot in general, please reach out to our [support team](https://docs.github.com/en/support/contacting-github-support/creating-a-support-ticket#creating-a-support-ticket).
