### ISSUE TITLE
[Bug] The Copilot sign-up link under Prerequisites at is wrong

### ISSUE THREAD

**Issue by ExtraneousUser** [skills/copilot-codespaces-vscode#18]
The Copilot sign-up link under Prerequisites at https://github.com/skills/copilot-codespaces-vscode is wrong. The link sends you to a page that only offers a 30-day trial, not the stated 60-day trial.

![Screenshot](https://github.com/skills/copilot-codespaces-vscode/assets/139809150/f3bdea56-fefb-4ae6-8df9-a0fc986d44f2)

**Comment by wonde23** [comment]
May I get the link for 60 day trial?

**Comment by itsPriyam07** [comment]
yes

**Comment by freyja92** [comment]
same

**Comment by AuregaX** [comment]
Also accounts that used to be in the beta are not able to sign up for the 30 day trial. so im unable to do this module unless I pay for it, which Im not inclined to do at this point.

**Comment by jamesnnannah** [comment]
I cannot see any next steps after the refresh. I saw the update of the readme.md but it contained no next-steps for the course. Any ideas?

**Comment by AhmedSyeda** [comment]
I paid for the trial version still I don't see the git copilot icon in codespace. Now, what happens to my trial? Do I get billed after 30 days?

**Comment by sinsukehlab** [comment]
Resolved in #53

**Comment by cmwilson21** [comment]
Closing this issue since the time frame has been updated in the course 👍 

@AhmedSyeda If you are still having issues, please reach out to our awesome [support team](https://support.github.com/request).
