### ISSUE TITLE
[Feature]Defaultwert in Eingabemasken ist bei Anklicken direkt markiert

### ISSUE THREAD

**Issue by A2905K** [skills/copilot-codespaces-vscode#212]
### Summary

A clear and concise description of what the problem is, and what you solution you want.

Dort wo eine Zahl eingegeben werden kann, steht standardmäßig eine Null als default drin. Es wäre für den Workflow einfacher, wenn beim Klicken in das Feld der Nullwert direkt markiert wäre, damit er durch Eingabe überschrieben werden kann. Jetzt klickt man in das Feld und landet hinter der Null, muss diese löschen und dann denn neuen Wert eingeben. 

### Changes

What changes this feature would introduce. Any risks these changes involve. Any alternative solutions or features you've considered.

**Comment by akhilesh511** [comment]
Yrdtydyiugjhljhnkhghjl chjghjo Gghu Gjk
 Vgufuy. Huvuygiug

**Comment by akhilesh511** [comment]
Iguigyiiygigg

**Comment by akhilesh511** [comment]
Trrityrrtr

**Comment by akhilesh511** [comment]
Gghhj
