### ISSUE TITLE
[Feature]Lieferantenübersicht um Summenzeile ergänzen

### ISSUE THREAD

**Issue by A2905K** [skills/copilot-codespaces-vscode#215]
### Summary

A clear and concise description of what the problem is, and what you solution you want.

In der Lieferantenübersicht werden basierend auf den Produkten im Auswahlzeitraum die Stückzahl des Artikel pro Lieferant aufgelistet. Hier wäre es cool, wenn unten noch eine Summe des Warenborbs angezeigt werden würde. 

### Changes

What changes this feature would introduce. Any risks these changes involve. Any alternative solutions or features you've considered.

**Comment by akhilesh511** [comment]
K
Cshksch
Adkjcjl
Davjjlvbcnf cjk
