### ISSUE TITLE
Pls help me solve

### ISSUE THREAD

**Issue by Brainz2024** [skills/copilot-codespaces-vscode#226]
### [Summary](url)
![Screenshot_20241213-014602_Chrome](https://github.com/user-attachments/assets/1fe73cff-c8c1-415f-8da5-09aaaf634ae0)

A clear and concise description of what the problem is, and what you solution you want.

### Changes

What changes this feature would introduce. Any risks these changes involve. Any alternative solutions or features you've considered.

**Comment by nontombi2002** [comment]
Task A: Expose an API (Back-End Focus)
Develop a RESTful API for a Task Management System. The API should allow users to:
1. Create a Task:
- Endpoint: POST /tasks
- Request Body:
{
"title": "string",
"description": "string",
"status": "string" // e.g., "To Do", "In Progress", "Done"
}
2. Retrieve All Tasks:
- Endpoint: GET /tasks
3. Update a Task:
- Endpoint: PUT /tasks/{id}
- Request Body:
{
"title": "string",
"description": "string",
"status": "string"
}
4. Delete a Task:
- Endpoint: DELETE /tasks/{id}
Additional Requirements:
- Use a database or an in-memory store to persist tasks.
- Follow SOLID principles to design clean and scalable code.
- Provide detailed instructions on how to run your application locally.
