### ISSUE TITLE
[Bug] Page does not correctly refresh to Step3

### ISSUE THREAD

**Issue by machieser56** [skills/copilot-codespaces-vscode#27]
### Summary

I followed the steps until the end of step 2 and refreshed the page as specified, but the ReadMe does not update to step 3

### How to reproduce

1. Follow the instructions including activity "step 2: Push code to your repository from the codespace"
2. Wait the 60 seconds as given by the instructions
3. Refresh
4. Nothing happens, ReadMe still displays "step 2", I've reloaded multiple times and waited far longer than a minute.

### Additional context
Screenshot of the state of my repository (including the skill.js file pushed)
![grafik](https://github.com/skills/copilot-codespaces-vscode/assets/48470377/a26b88df-527a-4c19-9d95-1d36e98f49bf)

**Comment by sinsukehlab** [comment]
Name the file `skills.js`, not `skill.js`.
